services:
  spring-boot-app:
    image: openjdk:18
    container_name: spring-boot-app
    working_dir: /app
    volumes:
      - ./target/customer-0.0.1-SNAPSHOT.jar:/app/customer-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/customerdb?useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - database
    command: [ "java", "-jar", "customer-0.0.1-SNAPSHOT.jar" ]
  database:
    image: 'postgres:17.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'